services:
  emitter:
    build: ./emitter
    container_name: friday_emitter
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus:latest
    container_name: friday_prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - emitter

  grafana:
    image: grafana/grafana:latest
    container_name: friday_grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
